spring.application.name=TAB-Lab1_excercise
spring.datasource.url=jdbc:postgresql://localhost:5432/flowers-postgres
spring.datasource.username=bar
spring.datasource.password=foo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_SERIALIZABLE